In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import backend.config as config

In [2]:
ticker = "MSFT"
interval = "daily"
start_date = "2026-03-10"
end_date = "2026-03-10"

bronze_path = f"../../../data/bronze/{ticker}/{interval}/news.parquet"
silver_path = f"../../../data/silver/{ticker}/{interval}/data.parquet"
gold_path = f"../../../data/gold/{ticker}/{interval}/baseline_results.parquet"

In [3]:
pd.Timestamp.today().normalize()

Timestamp('2026-03-10 00:00:00')

In [4]:
start_date = "2026-03-10"
pd.to_datetime(start_date).date() == pd.Timestamp.today().date()

True

In [3]:
from backend.pipeline.bronze_pipeline import update_bronze_pipeline

update_bronze_pipeline(ticker)

[MSFT] --- BRONZE PIPELINE ---
[MSFT] Prices are already up to date.
[MSFT] Fetching news from 2026-03-10 to 2026-03-11...
[MSFT] News saved. Total rows in file: 2010

In [3]:
from backend.pipeline.silver_pipeline import update_silver_pipeline

update_silver_pipeline(ticker)

/Users/gabrielvictorgomesferreira/artificial_intelligence/isu_classes/projects/Trading-Engine/.venv/lib/python3.14/site-packages/langchain_core/_api/deprecation.py:25: UserWarning: Core Pydantic V1 functionality isn't compatible with Python 3.14 or greater.
  from pydantic.v1.fields import FieldInfo as FieldInfoV1

[MSFT] (Equity) Updating features from 2025-12-11...
[MSFT] No new news to score since 2026-03-11 00:00:00.
[MSFT] Silver updated. Total rows: 1786

/Users/gabrielvictorgomesferreira/artificial_intelligence/isu_classes/projects/Trading-Engine/src/backend/pipeline/silver_pipeline.py:16: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  processing_df['Sentiment'] = processing_df['Sentiment'].ffill().fillna(0.0)

In [10]:
df_news = pd.read_parquet(silver_path, engine='pyarrow')
df_news.sort_values(by=['Date'], ascending=False).head()

,Date,Ticker,Adj Close,Close,High,Low,Open,Volume,RSI,SMA_20,SMA_50,EMA_20,MACD,MACD_Signal,MACD_Hist,Sentiment
1532,2026-03-10,MSFT,405.760010,405.760010,410.200012,402.929993,410.029999,31655300,56.271826,400.923260,433.825156,407.309299,-6.543235,-10.398328,3.855093,0.0
1531,2026-03-09,MSFT,409.410004,409.410004,410.209991,403.500000,404.920013,30073800,48.031303,401.547499,436.187400,407.678091,-7.334439,-11.474952,4.140513,NaN
1530,2026-03-06,MSFT,408.959991,408.959991,413.049988,408.510010,409.200012,31123900,49.092230,401.134000,437.736200,407.495784,-8.424030,-12.510080,4.086050,NaN
1529,2026-03-05,MSFT,410.679993,410.679993,411.609985,404.399994,404.420013,39001300,45.277965,400.369501,439.255400,407.341657,-9.646393,-13.531592,3.885199,NaN
1528,2026-03-04,MSFT,405.200012,405.200012,411.029999,400.309998,401.269989,35808000,40.762838,400.545001,440.760201,406.990254,-11.241389,-14.502892,3.261503,NaN

In [11]:
df_news['Sentiment'].value_counts()

Sentiment
0.0    1
Name: count, dtype: int64

In [ ]:
# import backend.config as config
# from alpaca.data.historical.news import NewsClient
# from alpaca.data.requests import NewsRequest

# ALPACA_API_KEY = config.ALPACA_API_KEY
# ALPACA_SECRET_KEY = config.ALPACA_SECRET_KEY
# client = NewsClient(ALPACA_API_KEY, ALPACA_SECRET_KEY, raw_data=True)
# request_params = NewsRequest(
#     symbols=ticker,
#     start=start_date,
#     end=end_date,
#     limit=2000
# )
# news_data = client.get_news(request_params)

In [1]:
# news_list = news_data.get('news', [])
# df_news = pd.DataFrame(news_list)
# df_news.head()

In [2]:
# len(news_list)

In [3]:
# df_clean = df_news[['id', 'headline', 'summary', 'created_at']].copy()
# df_clean.insert(1, 'Ticker', ticker)
# df_clean.insert(2, 'Date',
#                 pd.to_datetime(df_clean['created_at']).dt.tz_localize(None).dt.normalize()
#                 )
# df_clean

In [4]:
# if len(news_list) > 0:
#     df_news = pd.DataFrame(news_list)
#     # Now you can safely do things like df_news['id']
# else:
#     print(f"No news articles found for {ticker}.")
#     # Create an empty DF with correct columns so the rest of your pipeline doesn't crash
#     df_news = pd.DataFrame(columns=['id', 'headline', 'summary', 'content', 'symbols'])

In [5]:
df_news = pd.read_parquet(bronze_path, engine='pyarrow').reset_index(drop=True)
print(f"News DataFrame shape: {df_news.shape}")
df_news.sort_values(by='created_at', ascending=False).head()

News DataFrame shape: (1999, 6)

,id,Ticker,Date,headline,summary,created_at
1998,51140635,MSFT,2026-03-09,Cathie Wood's ARK Warns Of AI Hunger Games: 'N...,The explosive boom in AI is creating enormous ...,2026-03-09 19:11:51+00:00
1997,51138854,MSFT,2026-03-09,Nvidia's $4 Trillion Empire Rests On A Country...,Nvidia&#39;s chips are built by TSM in Taiwan ...,2026-03-09 18:11:09+00:00
1996,51137612,MSFT,2026-03-09,10 Information Technology Stocks With Whale Al...,,2026-03-09 17:35:18+00:00
1995,51136885,MSFT,2026-03-09,'OpenAI Buying AI Security Startup Promptfoo T...,,2026-03-09 17:11:17+00:00
1994,51133658,MSFT,2026-03-09,Crude Above $100 Sends Inflation Odds On Fire ...,Inflation expectations surged on prediction ma...,2026-03-09 15:52:35+00:00

In [6]:
df_news['headline'][0]

'DA Davidson Maintains Buy on Microsoft, Raises Price Target to $650'

In [7]:
df_news['summary'][0]

''

In [8]:
grouped_news = df_news.groupby('Date')
grouped_news.size()

Date
2025-07-31     4
2025-08-01    15
2025-08-02     5
2025-08-03     2
2025-08-04     7
              ..
2026-03-05    17
2026-03-06    12
2026-03-07     4
2026-03-08     1
2026-03-09     9
Length: 212, dtype: int64

In [9]:
from langchain_openai import ChatOpenAI
from langchain_core.prompts import PromptTemplate



llm = ChatOpenAI(model="gpt-4o-mini", temperature=0, api_key=config.OPENAI_KEY)
template = """
Analyze these headlines for {ticker}. 
Score the narrative from -1.0 (Panic/Crisis) to 1.0 (Euphoria/Growth).
Headlines: {news}
Return ONLY the numerical score.
"""
prompt = PromptTemplate.from_template(template)

daily_scores = []

print(f"Computing LLM Sentiment across {len(grouped_news)} trading days...")

for date, group in grouped_news:
    headlines = "\n- ".join(group['headline'].dropna().tolist())

    print(f"Date: {date.date()}, Headlines: {len(group)}")

    

    response = llm.invoke(prompt.format(ticker=ticker, news=headlines))
    score = float(response.content.strip())

    
    daily_scores.append({'Date': date, 'Sentiment': score})

    break
    
sentiment_df = pd.DataFrame(daily_scores).set_index('Date')

/Users/gabrielvictorgomesferreira/artificial_intelligence/isu_classes/projects/Trading-Engine/.venv/lib/python3.14/site-packages/langchain_core/_api/deprecation.py:25: UserWarning: Core Pydantic V1 functionality isn't compatible with Python 3.14 or greater.
  from pydantic.v1.fields import FieldInfo as FieldInfoV1

Computing LLM Sentiment across 212 trading days...
Date: 2025-07-31, Headlines: 4

In [10]:
sentiment_df

            Sentiment
Date
2025-07-31        0.7

In [11]:
print(headlines)

DA Davidson Maintains Buy on Microsoft, Raises Price Target to $650
- MAGS ETF Hits Record High As Microsoft And Meta Earnings Fuel Tech Rally
- ''Trump Administration To Expand Price Support For U.S. Rare Earths Projects; Trump Administration's Price Support For MP Materials Was Not A 'One-off' And Will Be Extended To Other Companies, Sources Say' - Reuters Exclusive
- Palo Alto Networks Downgraded On Strategic Concerns Post CyberArk Deal; Stocks Slide Over 5%

In [13]:
group['headline'][0]

'DA Davidson Maintains Buy on Microsoft, Raises Price Target to $650'

In [14]:
bronze_news_path = f"../../../data/bronze/{ticker}/{interval}/news.parquet"
df_news = pd.read_parquet(bronze_news_path)
df_news.head()

,id,Ticker,Date,headline,summary,created_at
0,46771500,MSFT,2025-07-31,"DA Davidson Maintains Buy on Microsoft, Raises...",,2025-07-31 18:57:51+00:00
1,46772973,MSFT,2025-07-31,MAGS ETF Hits Record High As Microsoft And Met...,The Roundhill Magnificent Seven ETF surged to ...,2025-07-31 19:44:30+00:00
2,46773014,MSFT,2025-07-31,''Trump Administration To Expand Price Support...,,2025-07-31 19:45:50+00:00
3,46773476,MSFT,2025-07-31,Palo Alto Networks Downgraded On Strategic Con...,Palo Alto&#39;s CyberArk acquisition sparks co...,2025-07-31 19:58:53+00:00
4,46781140,MSFT,2025-08-01,Tim Cook Says Apple Is 'Very Open' To AI Acqui...,Apple CEO Tim Cook said the company is &#34;ve...,2025-08-01 02:04:55+00:00

In [15]:
import os
import pandas as pd
from backend.utils import calculate_lookback_date
from backend.data_processor.indicators import apply_indicators
from backend.data_processor.sentiment import compute_sentiment_feature

bronze_path = f"../../../data/bronze/{ticker}/{interval}/data.parquet"
silver_dir = f"../../../data/silver/{ticker}/{interval}"
silver_path = f"{silver_dir}/data.parquet"

In [16]:
raw_df = pd.read_parquet(bronze_path, engine='pyarrow')
raw_df['Date'] = pd.to_datetime(raw_df['Date'])


features_df = pd.read_parquet(silver_path, engine='pyarrow')
features_df['Date'] = pd.to_datetime(features_df['Date'])
    
# Grab the date of the last calculated feature
last_feature_date = features_df['Date'].iloc[-1]

# Calculate the exact calendar date we need to prime the math, 
# accounting for crypto 24/7 vs equity holidays
prime_date, asset_class = calculate_lookback_date(ticker, last_feature_date, lookback_days=60)

print(f"[{ticker}] ({asset_class}) Updating features. Priming data from {prime_date.strftime('%Y-%m-%d')}...")

# Slice the raw data from our calculated prime date forward
processing_df = raw_df[raw_df['Date'] >= prime_date].copy()
is_incremental = True


# Compute indicators
processing_df = apply_indicators(processing_df)

# Compute and merge the AI Sentiment Feature
sentiment_df = compute_sentiment_feature(ticker, interval)

# Merge the sentiment column into your main OHLCV+Indicators dataframe
processing_df = processing_df.join(sentiment_df, how='left')
processing_df['Sentiment'] = (
    processing_df['Sentiment']
    .ffill()
    .fillna(0.0)
)
processing_df.head()

[MSFT] (Equity) Updating features. Priming data from 2025-12-09...
Computing LLM Sentiment across 212 trading days...

KeyboardInterrupt:

In [ ]:
processing_df.sort_values(by='Date', ascending=False).head()

,Date,Ticker,Adj Close,Close,High,Low,Open,Volume,RSI,SMA_20,SMA_50,EMA_20,MACD,MACD_Signal,MACD_Hist,Sentiment
1552,2026-03-09,MSFT,409.410004,409.410004,410.209991,403.500000,404.920013,30073800,48.031303,401.547499,436.187400,407.700918,-7.434800,-11.621850,4.187050,0.0
1551,2026-03-06,MSFT,408.959991,408.959991,413.049988,408.510010,409.200012,31123900,49.092230,401.134000,437.736200,407.521014,-8.532386,-12.668612,4.136226,0.0
1550,2026-03-05,MSFT,410.679993,410.679993,411.609985,404.399994,404.420013,39001300,45.277965,400.369501,439.255400,407.369543,-9.763379,-13.702669,3.939290,0.0
1549,2026-03-04,MSFT,405.200012,405.200012,411.029999,400.309998,401.269989,35808000,40.762838,400.545001,440.760201,407.021075,-11.367688,-14.687491,3.319803,0.0
1548,2026-03-03,MSFT,403.929993,403.929993,406.700012,392.670013,393.140015,38199200,39.266790,400.845500,442.335801,407.212766,-12.692060,-15.517442,2.825382,0.0

In [ ]:
processing_df[processing_df['Sentiment'] != 0]

Empty DataFrame
Columns: [Date, Ticker, Adj Close, Close, High, Low, Open, Volume, RSI, SMA_20, SMA_50, EMA_20, MACD, MACD_Signal, MACD_Hist, Sentiment]
Index: []

In [ ]:
sentiment_df

Empty DataFrame
Columns: [Sentiment]
Index: []